name: Python CI

on:
  pull_request:
    branches: [ main, master ]
    types: [opened, synchronize, reopened]
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    # Add the permissions block here for the 'build' job
    permissions:
      checks: write
      pull-requests: write

    strategy:
      matrix:
        python-version: ['3.11']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest and generate report
      run: pytest --junitxml=test-results.xml tests/test_gemini_manifold.py || true

    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: test-results.xml
        check_name: Pytest Results (Python ${{ matrix.python-version }})